### ISSUE TITLE
i3xrocks-todo: Excessive Journalctl logging (needs a debug flag?)

### ISSUE THREAD

**Issue by eduncan911** [regolith-linux/regolith-desktop#539]
- [X] I've [run a search on the existing bug reports](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests) to make sure I'm not filing a duplicate (you can use the search box at the top left corner)
- [X] I've read [the Regolith documentation](https://regolith-linux.org/docs/) and didn't find any relevant topic
- [ ] I tried [asking on Slack](https://regolith-linux.org/interact/) (especially for configuration related issues)
^- Slack is not allowed at my workplace.

**Describe the bug**
Similar to #538, this `i3xrocks-todo` package *may be* logging excessively to `journalctl`.  Every 90 seconds, a new log entry appears.

I say, *may be* because I am not sure if this is a real error or not, since I haven't finished setting up this new machine. Please close if this is expected until I fill out the todo portion (which, I can't find any documentation on).

**To Reproduce**

1. Installed a fresh Pop_OS! today
2. Installed Regolith-desktop today
3. `sudo apt install i3xrocks-todo`
4. refresh i3wm session
5. `$ journalctl -f`

**Expected behavior**
Nothing is logged.  Only if you are running under some DEBUG flag or build should it echo its contents.

**Screenshots**
```
/usr/share/i3xrocks/todo: 10: printf: 0: not completely converted
```
...every 90 seconds.

**Configuration file(s)**
Nothing really.  But here's all I've done total:

```
$ cat ~/.config/regolith/Xresources 
Xft.dpi: 192
Xcursor.size: 48
i3-wm.bar.position: top

$ sudo apt search regolith | grep installed

i3xrocks/groovy,now 1.3.4-1 amd64 [installed,automatic]
regolith-compositor-picom-glx/groovy,now 1.1.3-1 amd64 [installed,automatic]
regolith-default-settings/groovy,now 1.0.5-1groovy amd64 [installed,automatic]
regolith-desktop-standard/groovy,now 2.106-1groovy amd64 [installed]
regolith-ftue/groovy,now 1.1.0-1 amd64 [installed,automatic]
regolith-gnome-flashback/groovy,now 2.6.2-1 amd64 [installed,automatic]
regolith-i3-gaps-config/groovy,now 2.8.4-1 amd64 [installed,automatic]
regolith-i3xrocks-config/groovy,now 3.5.6-1 amd64 [installed,automatic]
regolith-look-ayu/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-ayu-dark/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-ayu-mirage/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-cahuella/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-dracula/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-gruvbox/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-lascaille/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-nord/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-pop-os/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-solarized-dark/groovy,now 2.6.14-1 amd64 [installed]
regolith-look-ubuntu/groovy,now 2.6.14-1 amd64 [installed]
regolith-rofi-config/groovy,now 1.3.1-1 amd64 [installed,automatic]
regolith-rofication/groovy,now 1.3.1-1 amd64 [installed,automatic]
regolith-styles/groovy,now 2.6.14-1 amd64 [installed,automatic]
regolith-unclutter-xfixes/groovy,now 1.5-2 amd64 [installed,automatic]
remontoire/groovy,now 1.4.0-1 amd64 [installed,automatic]

$ sudo apt search i3xrocks | grep installed

i3xrocks/groovy,now 1.3.4-1 amd64 [installed,automatic]
i3xrocks-battery/groovy,now 3.5.6-1 amd64 [installed]
i3xrocks-cpu-usage/groovy,now 3.5.6-1 amd64 [installed,automatic]
i3xrocks-key-indicator/groovy,now 3.5.6-1 amd64 [installed]
i3xrocks-net-traffic/groovy 3.5.6-1 amd64 [installed,automatic]
i3xrocks-rofication/groovy,now 3.5.6-1 amd64 [installed,automatic]
i3xrocks-temp/groovy,now 3.5.6-1 amd64 [installed]
i3xrocks-time/groovy,now 3.5.6-1 amd64 [installed,automatic]
i3xrocks-todo/groovy,now 3.2.6-1ubuntu2 amd64 [installed]
i3xrocks-volume/groovy,now 3.5.6-1 amd64 [installed]
regolith-i3xrocks-config/groovy,now 3.5.6-1 amd64 [installed,automatic]
```

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 2.106-1groovy (desktop)
 - PPA url: [default: ppa:regolith-linux/release]
 - Host OS (for PPA): Pop_OS 20.10

**Additional context**

I recommend hiding these entries under a debug flag.

**Comment by kgilmer** [comment]
Thank you for the detailed bug report! I was not aware of this issue @eduncan911. This will get rolled into Regolith 1.5.3.
